---
version: '3.8'

services:
  openhab:
    build: .
    ports:
    - '8080:8080'
    - '8443:8443'
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      VERBOSE_TEMPLATE_BUILD: 'false'
      WATCH_TEMPLATES: 'true'
    volumes:
    - ./examples/configs:/usr/local/etc/openhab
