---
version: '3.8'

services:
  openhab:
    build: .
    ports:
    - '8080:8080'
    - '8443:8443'
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      WATCH_TEMPLATES: 'true'
    volumes:
    - ./examples/configs/items:/usr/local/etc/openhab/templates
    - ./examples/config_vars.yaml:/usr/local/etc/openhab/config_vars.yaml
    - ./examples/secret_vars.yaml:/usr/local/etc/openhab/secret_vars.yaml
