#!/usr/bin/with-contenv bash

set -euo pipefail

# using gosu as openhab already uses it during start
gosu openhab watchman --logfile=/dev/stdout watch-project "$CONFIGS_INPUT_DIR"
gosu openhab watchman -- trigger "$CONFIGS_INPUT_DIR" openhab -- build-openhab-configs
gosu openhab watchman shutdown-server
gosu openhab watchman --foreground --logfile=/dev/stdout watch-project "$CONFIGS_INPUT_DIR"
