#!/usr/bin/with-contenv bash

watchman --logfile=/dev/stdout watch-project "$TEMPLATES_INPUT_DIR"
watchman -- trigger "$TEMPLATES_INPUT_DIR" templates '**/*.tmpl' -- parse-templates
watchman shutdown-server
watchman --foreground --logfile=/dev/stdout watch-project "$TEMPLATES_INPUT_DIR"
