#!/usr/bin/with-contenv bash

watchman watch-project "$TEMPLATES_INPUT_DIR"
watchman -- trigger "$TEMPLATES_INPUT_DIR" templates '**/*.tmpl' -- parse-templates
watchman shutdown-server
watchman --foreground watch-project "$TEMPLATES_INPUT_DIR"
